apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-registry
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/bllsdclsz/telcoai-platform.git
    targetRevision: main
    path: platform/charts/mlflow-registry
    helm:
      releaseName: mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: telcoai-registry
  syncPolicy:
    automated: { prune: true, selfHeal: true }
